# yaml-language-server: https://www.schemastore.org/pnpm-workspace.json
packages:
  - 'packages/**'
  - '!**/_template/**'

catalog:
  tsdown: ^0.18.3
  tsx: ^4.21.0
  typescript: ^5.9.3

catalogs:
  dev:
    "@pandacss/dev": ^1.7.2
    "@pandacss/types": ^1.7.2