blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/amandaguthrie/monorepo-template-ts-pnpm/discussions
    about: Ask questions and discuss topics with other community members