name: 'Install'
description: 'Set Up Node.js and Run Install'

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v3
      with:
        version: 10

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24 # Node 24 uses npm 11.6.2; need a minimum NPM version of 11.5.2 for provenance
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'

    - name: Setup Git User
      shell: bash
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Install dependencies
      shell: bash
      run: pnpm install