name: Release Dev Snapshot

on:
  push:
    paths:
      - '.changeset/**'
      - 'packages/**'
    branches-ignore:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release-dev-snapshot:
    name: Release Dev Snapshot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Build packages
        run: pnpm build

      - name: Release to dev tag
        run: |
          pnpm release:dev:version
          pnpm release:dev:publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GH_PAT}}